# Generated by Django 4.2.7 on 2024-05-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='products',
            name='usage_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Инструкция по применению'),
        ),
    ]
