# Generated by Django 4.2.7 on 2024-05-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_composition_products_usage_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Противопоказания'),
        ),
    ]
